[versions]
camerax = "1.5.2"
calf = "0.9.0"
kotlinx-coroutines = "1.10.2"
kotlinx-coroutines-android = "1.10.2"
kotlinx-datetime = "0.7.1-0.6.x-compat"
kotlinx-io = "0.8.2"
kotlinx-collections-immutable = "0.4.0"
kotlinx-serialization-json = "1.9.0"
core-ktx = "1.17.0"
androidx-activity = "1.8.2" # Anything higher requires https://github.com/adamint/spotify-web-api-kotlin/issues/338
androidx-core-splashscreen = "1.2.0"
androidx-documentfile = "1.1.0"
androidx-test = "1.7.0"
androidx-test-ext-junit = "1.3.0"
lifecycle-runtime-ktx = "2.10.0"
lifecycle-runtime-compose = "2.10.0"
navigation-compose = "2.9.6"
androidxHiltNavigationCompose = "1.3.0"
media3 = "1.9.0"
material3 = "1.4.0"
room = "2.8.4"
turbine = "1.2.1"
appcompat = "1.7.1"
spotify-api-kotlin-core = "4.1.3"
paging = "3.3.6"
palette = "0.0.48"
coil = "3.3.0"
logging = "0.0.15"
maindispatcher-rule = "0.0.13"
trace = "0.0.5"
uievent = "0.0.7"
gradle-plugins = "0.0.54"

[libraries]
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
camera-compose = { group = "androidx.camera", name = "camera-compose", version.ref = "camerax" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
calf-permissions = { group = "com.mohamedrejeb.calf", name = "calf-permissions", version.ref = "calf" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidx-documentfile" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3"}
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3-ui-leanback = { group = "androidx.media3", name = "media3-ui-leanback", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-cast = { group = "androidx.media3", name = "media3-cast", version.ref = "media3" }
media3-transformer = { group = "androidx.media3", name = "media3-transformer", version.ref = "media3" }
media3-decoder = { group = "androidx.media3", name = "media3-decoder", version.ref = "media3" }
media3-datasource = { group = "androidx.media3", name = "media3-datasource", version.ref = "media3" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
spotify-api-kotlin-core = { group = "com.adamratzman", name = "spotify-api-kotlin-core", version.ref = "spotify-api-kotlin-core" }
paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
paging-testing = { group = "androidx.paging", name = "paging-testing", version.ref = "paging" }
palette-components = { group = "com.alexrdclement.palette", name = "palette-components", version.ref = "palette" }
palette-theme = { group = "com.alexrdclement.palette", name = "palette-theme", version.ref = "palette" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
logger-api = { group = "com.alexrdclement.logging", name = "logger-api", version.ref = "logging" }
logger-impl = { group = "com.alexrdclement.logging", name = "logger-impl", version.ref = "logging" }
loggable = { group = "com.alexrdclement.logging", name = "loggable", version.ref = "logging" }
maindispatcher-rule = { group = "com.alexrdclement.testing", name = "maindispatcher-rule", version.ref = "maindispatcher-rule" }
trace = { group = "com.alexrdclement.trace", name = "trace", version.ref = "trace" }
uievent = { group = "com.alexrdclement.uievent", name = "uievent", version.ref = "uievent" }

[plugins]
mediaplayground-android-feature = { id = "mediaplayground.android.feature" }
alexrdclement-android-application = { id = "com.alexrdclement.gradle.plugin.android.application", version.ref = "gradle-plugins" }
alexrdclement-android-application-compose = { id = "com.alexrdclement.gradle.plugin.android.application.compose", version.ref = "gradle-plugins" }
alexrdclement-android-library = { id = "com.alexrdclement.gradle.plugin.android.library", version.ref = "gradle-plugins" }
alexrdclement-android-library-compose = { id = "com.alexrdclement.gradle.plugin.android.library.compose", version.ref = "gradle-plugins" }
alexrdclement-android-library-test-fixtures = { id = "com.alexrdclement.gradle.plugin.android.library.test.fixtures", version.ref = "gradle-plugins" }
alexrdclement-android-test = { id = "com.alexrdclement.gradle.plugin.android.test", version.ref = "gradle-plugins" }
alexrdclement-android-hilt = { id = "com.alexrdclement.gradle.plugin.android.hilt", version.ref = "gradle-plugins" }
alexrdclement-android-hilt-test-fixtures = { id = "com.alexrdclement.gradle.plugin.android.hilt.test.fixtures", version.ref = "gradle-plugins" }
alexrdclement-github-release = { id = "com.alexrdclement.gradle.plugin.github.release", version.ref = "gradle-plugins" }
alexrdclement-kotlin-multiplatform-library = { id = "com.alexrdclement.gradle.plugin.kotlin.multiplatform.library", version.ref = "gradle-plugins" }
alexrdclement-kotlin-serialization = { id = "com.alexrdclement.gradle.plugin.kotlin.serialization", version.ref = "gradle-plugins" }
alexrdclement-android-room = { id = "com.alexrdclement.gradle.plugin.android.room", version.ref = "gradle-plugins" }
alexrdclement-jvm-library = { id = "com.alexrdclement.gradle.plugin.jvm.library", version.ref = "gradle-plugins" }

[bundles]
