[versions]
android-desugar-jdk-libs = "2.0.4"
android-gradle-plugin = "8.5.1"
android-tools = "31.2.0"
compose-bom = "2024.06.00"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.23"
kotlinx-coroutines = "1.7.2"
kotlinx-coroutines-android = "1.7.3"
kotlinx-io = "0.3.1"
kotlinx-serialization-json = "1.6.0"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-activity = "1.8.2"
androidx-documentfile = "1.0.1"
androidx-test = "1.5.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.7.0"
lifecycle-runtime-compose = "2.7.0"
navigation-compose = "2.7.7"
hilt = "2.48"
androidxHiltNavigationCompose = "1.1.0"
media3 = "1.2.1"
material3 = "1.2.0"
turbine = "1.1.0"
tv-foundation = "1.0.0-alpha10"
tv-material = "1.0.0-alpha10"
appcompat = "1.6.1"
org-jetbrains-kotlin-jvm = "1.9.0"
spotify-api-kotlin-core = "4.1.3"
uiTooling = "1.6.1"
paging = "3.2.1"
coil = "2.4.0"
ui-playground-components = "0.0.1"

[libraries]
android-desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "android-desugar-jdk-libs" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidx-documentfile" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3"}
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3-ui-leanback = { group = "androidx.media3", name = "media3-ui-leanback", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-cast = { group = "androidx.media3", name = "media3-cast", version.ref = "media3" }
media3-transformer = { group = "androidx.media3", name = "media3-transformer", version.ref = "media3" }
media3-decoder = { group = "androidx.media3", name = "media3-decoder", version.ref = "media3" }
media3-datasource = { group = "androidx.media3", name = "media3-datasource", version.ref = "media3" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "tv-foundation" }
tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tv-material" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
spotify-api-kotlin-core = { group = "com.adamratzman", name = "spotify-api-kotlin-core", version.ref = "spotify-api-kotlin-core" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
ui-playground-components = { group = "com.alexrdclement.uiplayground", name = "ui-playground-components", version.ref = "ui-playground-components" }

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }

mediaplayground-android-application = { id = "mediaplayground.android.application", version = "unspecified" }
mediaplayground-android-application-compose = { id = "mediaplayground.android.application.compose", version = "unspecified" }
mediaplayground-android-feature = { id = "mediaplayground.android.feature", version = "unspecified" }
mediaplayground-android-hilt = { id = "mediaplayground.android.hilt", version = "unspecified" }
mediaplayground-android-hilt-test-fixtures = { id = "mediaplayground.android.hilt.test.fixtures", version = "unspecified" }
mediaplayground-android-library = { id = "mediaplayground.android.library", version = "unspecified" }
mediaplayground-android-library-compose = { id = "mediaplayground.android.library.compose", version = "unspecified" }
mediaplayground-android-library-test-fixtures = { id = "mediaplayground.android.library.test.fixtures", version = "unspecified" }
mediaplayground-android-test = { id = "mediaplayground.android.test", version = "unspecified" }
mediaplayground-jvm-library = { id = "mediaplayground.jvm.library", version = "unspecified" }

[bundles]
